name: Bug Report
description: Laporkan bug
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Deskripsi
      description: Jelaskan bug
    validations:
      required: true
  - type: input
    id: steps
    attributes:
      label: Langkah reproduksi
  - type: input
    id: expected
    attributes:
      label: Ekspektasi
  - type: input
    id: actual
    attributes:
      label: Aktual
