name: Feature Request
description: Ajukan fitur
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Ringkasan
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Detail
